### PR TITLE
fix: color mode

### LINKED ISSUE #482: fix: Dark Mode bug
### 🐛 The bug

I select dark mode, refresh the page, it comes as light mode, then I click on any button on the devetools, and it "forces" the selected mode. This has been happening from many versions of devtools back.

Browser: Chrome
OS: Windows 11 Home lastest update

### 🛠️ To reproduce

None 

### 🌈 Expected behavior

Dark mode being persisted after a refresh, and the light/dark button always working.

### ℹ️ Additional context

_No response_

### PR DESCRIPTION
**Pull request by arashsheyda**
This PR fixes the glitch between darkMode and lightMode (closes #482) by removing `@nuxtjs/color-mode` and standardizing on `useColorMode` from `@vueuse`
- plus a custom storageKey (`nuxt-devtools-color-mode`) is now used for devtools.

### CODE REVIEW

File: packages/devtools/client/components/ServerRouteDetails.vue [hunk 1]
```diff
@@ -544,7 +545,7 @@ const copy = useCopy()
         <JsonEditorVue
           v-else-if="selectedTabInput === 'json'"
           v-model="routeInputBodyJSON"
-          :class="[$colorMode.value === 'dark' ? 'jse-theme-dark' : 'light']"
+          :class="[colorMode === 'dark' ? 'jse-theme-dark' : 'light']"
```
Comment (manniL) [inline packages/devtools/client/components/ServerRouteDetails.vue:548]: Tiny nit

```suggestion
          :class="colorMode === 'dark' ? 'jse-theme-dark' : 'light'"
```

File: packages/devtools/client/components/ServerTaskDetails.vue [hunk 2]
```diff
@@ -310,7 +311,7 @@ const copy = useCopy()
         <JsonEditorVue
           v-else-if="selectedTabInput === 'json'"
           v-model="routeInputBodyJSON"
-          :class="[$colorMode.value === 'dark' ? 'jse-theme-dark' : 'light']"
+          :class="[colorMode === 'dark' ? 'jse-theme-dark' : 'light']"
```
Comment (manniL) [inline packages/devtools/client/components/ServerTaskDetails.vue:314]:
```suggestion
          :class="colorMode === 'dark' ? 'jse-theme-dark' : 'light'"
```

File: packages/devtools/client/components/TimelineArgumentView.vue [hunk 3]
```diff
@@ -69,7 +70,7 @@ const copy = useCopy()
             v-bind="$attrs"
             class="json-editor-vue"
             :class="[
-              $colorMode.value === 'dark' ? 'jse-theme-dark' : '',
+              colorMode === 'dark' ? 'jse-theme-dark' : '',
             ]"
```
Comment (manniL) [inline packages/devtools/client/components/TimelineArgumentView.vue:74]: And probably also here 😋
