### PR TITLE
fix: analyze build without git

### LINKED ISSUE #318: fix(Build analyze): Start a new build without Git
### 🐛 The bug

Creating a new nuxt project does not initialize git by default, and when I use devtool for build analysis, clicking start a new build does not respond. An error message appears on the command line:

```
 ERROR  [nuxt-devtools] RPC error on executing "generateAnalyzeBuildName": fatal: not a git repository (or any of the parent directories): .git                                  15:47:27


  
  at Object.action (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:6000:25)
  at PluginStore.exec (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:6027:25)
  at /D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:3449:43
  at new Promise (<anonymous>)
  at GitExecutorChain.handleTaskData (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:3447:16)
  at GitExecutorChain.<anonymous> (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:3431:44)
  at Generator.next (<anonymous>)
  at fulfilled (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:2244:24)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 🛠️ To reproduce

Any nuxt project without git

### 🌈 Expected behavior

I think maybe the build analysis doesn't need to rely on git, it seems to be an error in generating the build name, maybe we can get a build name from somewhere else, like `package.json`?

### ℹ️ Additional context

_No response_

### PR DESCRIPTION
**Pull request by Jannchie**
close #318

### CODE REVIEW

File: packages/devtools/src/server-rpc/analyze-build.ts [hunk 1]
```diff
@@ -63,14 +63,20 @@ export function setupAnalyzeBuildRPC({ nuxt, refresh, ensureDevAuthToken }: Nuxt
...
+      const branchName = branch.current || 'head'
+      const sha = await git.revparse(['--short', 'HEAD'])
+      const isWorkingTreeClean = (await git.status()).isClean()
+      if (isWorkingTreeClean)
+        return `${branchName}#${sha}`
+      return `${branchName}#${sha}-dirty`
+    }
+    catch (e) {
+      // if the git is not available, fallback to iso string
+      return new Date().toISOString()
```
Comment (antfu) [inline packages/devtools/src/server-rpc/analyze-build.ts:78]: We might need to do some normalization and replace non-letters to `-` as chars like `:` are not valid path

Comment (Jannchie) [reply packages/devtools/src/server-rpc/analyze-build.ts]: I've fixed it.
