### PR TITLE
fix: blurred font

### LINKED ISSUE #411: fix: window下工具条移动到左右侧导致字体模糊
### 🐛 The bug

动画

### 🛠️ To reproduce

无

### 🌈 Expected behavior

预期正常显示

### ℹ️ Additional context

chrome version: 118

补充:问题解决方案可参考这里:https://github.com/chokcoco/iCSS/issues/160

### PR DESCRIPTION
**Pull request by starknt**
close #411
Eliminate the side effects of element transformations by calculating the offset of the element.

https://github.com/nuxt/devtools/assets/64941905/316e24b8-fa84-4b41-b1bf-156e4e790fa0

### CODE REVIEW

File: packages/devtools/src/runtime/plugins/view/Main.vue [hunk 1]
```diff
@@ -255,8 +257,9 @@ const iframeStyle = computed(() => {
   const maxHeight = windowSize.height - marginVertical
 
   const style: CSSProperties = {
+    position: 'fixed',
     zIndex: -1,
-    pointerEvents: isDragging.value ? 'none' : 'auto',
+    pointerEvents: isDragging.value || !state.value.open ? 'none' : 'auto',
```
Comment (starknt) [inline packages/devtools/src/runtime/plugins/view/Main.vue:262]: I try use `isHidden`, but its value doesn't seem to change based on the `state`

**Review by antfu — APPROVED** [review]

**Comment by antfu** [comment]
Nice, thanks!
