### PR TITLE
fix(SideNav): logo text color in light mode

### LINKED ISSUE #536: Light mode (sidebar expended) logo text is white

### PR DESCRIPTION
**Pull request by arashsheyda**
close #536

### CODE REVIEW

File: packages/devtools/client/components/SideNav.vue [hunk 1]
```diff
@@ -83,7 +83,7 @@ onClickOutside(
         >
           <div i-logos-nuxt-icon h-6 w-6 />
           <template v-if="sidebarExpanded">
-            <span text="lg white" font-600>
+            <span text="lg black dark:white" font-600>
```
Comment (antfu) [inline packages/devtools/client/components/SideNav.vue:86]:
```suggestion
            <span text-lg font-600>
```

Would this works, that just inherit the parent color?

Comment (arashsheyda) [reply packages/devtools/client/components/SideNav.vue:86]: it would work but it's not white or black, it's kinda gray

Screenshot 2023-12-08 at 1 26 41 PM
Screenshot 2023-12-08 at 1 27 08 PM

Comment (antfu) [reply packages/devtools/client/components/SideNav.vue:86]: No it was great before this, thanks!

Comment (arashsheyda) [reply packages/devtools/client/components/SideNav.vue:86]: Thank you
